// A cache of all active NBA players to make player search auto filling possible
export const playerListImport = ["Maozinha Pereira","Taze Moore", "Matt Hurt", "Jaylin Galloway", "DJ Carton", "Izaiah Brockington","Amari Bailey", "Precious Achiuwa", "Jaylen Adams", "Steven Adams", "Bam Adebayo","LaMarcus Aldridge",
  "Ty-Shon Alexander", "Nickeil Alexander-Walker", "Grayson Allen", "Jarrett Allen",
  "Al-Farouq Aminu", "Kyle Anderson","Giannis Antetokounmpo", "Kostas Antetokounmpo",
  "Thanasis Antetokounmpo", "Carmelo Anthony", "Cole Anthony", "OG Anunoby", "Ryan Arcidiacono",
  "Trevor Ariza", "D.J. Augustin", "Deni Avdija","Deandre Ayton", "Udoka Azubuike", "Dwayne Bacon",
  "Marvin Bagley III", "LaMelo Ball", "Lonzo Ball","Mo Bamba", "Desmond Bane", "Harrison Barnes",
  "RJ Barrett", "Will Barton", "Keita Bates-Diop", "Nicolas Batum", "Aron Baynes", "Kent Bazemore",
  "Darius Bazley", "Bradley Beal", "Malik Beasley", "Jordan Bell", "DeAndre Bembry", "Davis Bertans",
  "Patrick Beverley", "Saddiq Bey", "Tyler Bey", "Khem Birch", "Goga Bitadze", "Bismack Biyombo",
  "Nemanja Bjelica", "Eric Bledsoe", "Keljin Blevins", "Bogdan Bogdanovic", "Bojan Bogdanovic",
  "Bol Bol", "Marques Bolden", "Jordan Bone", "Isaac Bonga", "Devin Booker", "Chris Boucher",
  "Brian Bowen II", "Avery Bradley", "Tony Bradley", "Jarrell Brantley", "Ignas Brazdeikis",
  "Mikal Bridges", "Miles Bridges", "Amida Brimah", "Oshae Brissett", "Malcolm Brogdon",
  "Armoni Brooks", "Dillon Brooks", "Bruce Brown", "Jaylen Brown", "Moses Brown",
  "Sterling Brown", "Charlie Brown Jr.", "Troy Brown Jr.", "Jalen Brunson", "Elijah Bryant",
  "Thomas Bryant", "Reggie Bullock", "Trey Burke", "Alec Burks", "Jimmy Butler", "Bruno Caboclo",
  "Devontae Cacok", "Kentavious Caldwell-Pope", "Facundo Campazzo", "Vlatko Cancar", "Devin Cannady",
  "Clint Capela", "Vernon Carey Jr.", "Jevon Carter", "Wendell Carter Jr.", "Michael Carter-Williams",
  "Alex Caruso", "Willie Cauley-Stein", "Chris Chiozza", "Marquese Chriss", "Gary Clark", "Brandon Clarke",
  "Jordan Clarkson", "Nicolas Claxton", "Amir Coffey", "John Collins", "Zach Collins", "Mike Conley",
  "Pat Connaughton", "Quinn Cook", "Tyler Cook", "DeMarcus Cousins", "Robert Covington", "Torrey Craig",
  "Jae Crowder", "Jarrett Culver", "Seth Curry", "Stephen Curry", "Nate Darling", "Anthony Davis", "Ed Davis",
  "Terence Davis", "DeMar DeRozan", "Gabriel Deck", "Dewayne Dedmon", "Matthew Dellavedova",
  "Donte DiVincenzo", "Mamadi Diakite", "Hamidou Diallo", "Gorgui Dieng", "Spencer Dinwiddie",
  "Luka Doncic", "Luguentz Dort", "Damyean Dotson", "Devon Dotson", "Sekou Doumbouya", "PJ Dozier",
  "Goran Dragic", "Andre Drummond", "Jared Dudley", "Kris Dunn", "Kevin Durant", "Anthony Edwards",
  "Carsen Edwards", "CJ Elleby", "Henry Ellenson", "Wayne Ellington", "Joel Embiid", "James Ennis III",
  "Drew Eubanks", "Dante Exum", "Tacko Fall", "Derrick Favors", "Cristiano Felicio", "Terrance Ferguson",
  "Bruno Fernando", "Yogi Ferrell", "Dorian Finney-Smith", "Malik Fitts", "Malachi Flynn", "Bryn Forbes",
  "Trent Forrest", "Evan Fournier", "De'Aaron Fox", "Robert Franks", "Tim Frazier", "Markelle Fultz",
  "Wenyen Gabriel", "Daniel Gafford", "Danilo Gallinari", "Langston Galloway", "Darius Garland",
  "Marc Gasol", "Rudy Gay", "Paul George", "Taj Gibson", "Harry Giles III", "Shai Gilgeous-Alexander",
  "Anthony Gill", "Freddie Gillespie", "Rudy Gobert", "Brandon Goodwin", "Aaron Gordon", "Eric Gordon",
  "Devonte' Graham", "Jerami Grant", "Danny Green", "Draymond Green", "JaMychal Green", "Javonte Green",
  "Jeff Green", "Josh Green", "Blake Griffin", "Kyle Guy", "Rui Hachimura", "Ashton Hagans",
  "Tyrese Haliburton", "Donta Hall", "Josh Hall", "R.J. Hampton", "Tim Hardaway Jr.", "James Harden",
  "Maurice Harkless", "Jared Harper", "Montrezl Harrell", "Gary Harris", "Jalen Harris", "Joe Harris",
  "Tobias Harris", "Shaquille Harrison", "Josh Hart", "Isaiah Hartenstein", "Udonis Haslem", "Jaxson Hayes",
  "Killian Hayes", "Gordon Hayward", "Juancho Hernangomez", "Willy Hernangomez", "Tyler Herro", "Buddy Hield",
  "George Hill", "Solomon Hill", "Nate Hinton", "Jaylen Hoard", "Aaron Holiday", "Jrue Holiday",
  "Justin Holiday", "Rondae Hollis-Jefferson", "Richaun Holmes", "Rodney Hood", "Al Horford",
  "Talen Horton-Tucker", "Danuel House Jr.", "Dwight Howard", "Markus Howard", "Kevin Huerter",
  "Elijah Hughes", "De'Andre Hunter", "Chandler Hutchison", "Serge Ibaka", "Andre Iguodala", "Ersan Ilyasova",
  "Joe Ingles", "Brandon Ingram", "Kyrie Irving", "Jonathan Isaac", "Wes Iwundu", "Frank Jackson",
  "Josh Jackson", "Justin Jackson", "Reggie Jackson", "Jaren Jackson Jr.", "Justin James", "LeBron James",
  "Mike James", "DaQuan Jeffries", "Ty Jerome", "Isaiah Joe", "Alize Johnson", "Cameron Johnson",
  "James Johnson", "Keldon Johnson", "Stanley Johnson", "Tyler Johnson", "Nikola Jokic", "Damian Jones",
  "Mason Jones", "Tre Jones", "Tyus Jones", "Derrick Jones Jr.", "DeAndre Jordan", "Cory Joseph",
  "Mfiondu Kabengele", "Frank Kaminsky", "Enes Kanter", "Luke Kennard", "Louis King", "Maxi Kleber",
  "Nathan Knight", "Kevin Knox II", "John Konchar", "Furkan Korkmaz", "Luke Kornet", "Rodions Kurucs",
  "Kyle Kuzma", "Zach LaVine", "Anthony Lamb", "Jeremy Lamb", "Romeo Langford", "Jake Layman", "Caris LeVert",
  "T.J. Leaf", "Jalen Lecque", "Damion Lee", "Saben Lee", "Alex Len", "Kawhi Leonard", "Meyers Leonard",
  "Kira Lewis Jr.", "Damian Lillard", "Nassir Little", "Kevon Looney", "Brook Lopez", "Robin Lopez",
  "Didi Louzada", "Kevin Love", "Kyle Lowry", "Timothe Luwawu-Cabarrot", "Trey Lyles", "Will Magnay",
  "Thon Maker", "Theo Maledon", "Karim Mane", "Terance Mann", "Nico Mannion", "Boban Marjanovic",
  "Lauri Markkanen", "Naji Marshall", "Caleb Martin", "Cody Martin", "Jeremiah Martin", "Kelan Martin",
  "Kenyon Martin Jr.", "Frank Mason", "Garrison Mathews", "Dakota Mathias", "Wesley Matthews",
  "Tyrese Maxey", "Skylar Mays", "Patrick McCaw", "CJ McCollum", "T.J. McConnell", "Jaden McDaniels",
  "Jalen McDaniels", "Doug McDermott", "Sean McDermott", "JaVale McGee", "Rodney McGruder",
  "Alfonzo McKinnie", "Jordan McLaughlin", "Ben McLemore", "Nicolo Melli", "De'Anthony Melton",
  "Sam Merrill", "Chimezie Metu", "Khris Middleton", "Darius Miller", "Patty Mills", "Paul Millsap",
  "Shake Milton", "Donovan Mitchell", "Adam Mokoka", "Malik Monk", "E'Twaun Moore", "Ja Morant",
  "Juwan Morgan", "Markieff Morris", "Monte Morris", "Marcus Morris Sr.", "Mychal Mulder", "Dejounte Murray",
  "Jamal Murray", "Mike Muscala", "Svi Mykhailiuk", "Abdel Nader", "Larry Nance Jr.", "Aaron Nesmith",
  "Raul Neto", "Georges Niang", "Zeke Nnaji", "Nerlens Noel", "Jaylen Nowell", "Frank Ntilikina",
  "Kendrick Nunn", "James Nunnally", "Jusuf Nurkic", "David Nwaba", "Jordan Nwora", "Royce O'Neale",
  "Semi Ojeleye", "Jahlil Okafor", "Chuma Okeke", "Josh Okogie", "Onyeka Okongwu", "Isaac Okoro",
  "KZ Okpala", "Victor Oladipo", "Cameron Oliver", "Kelly Olynyk", "Miye Oni", "Cedi Osman",
  "Daniel Oturu", "Kelly Oubre Jr.", "Jabari Parker", "Eric Paschall", "Anzejs Pasecniks",
  "Patrick Patterson", "Justin Patton", "Chris Paul", "Cameron Payne", "Elfrid Payton",
  "Gary Payton II", "Norvel Pelle", "Reggie Perry", "Theo Pinson", "Mason Plumlee", "Jakob Poeltl",
  "Vincent Poirier", "Aleksej Pokusevski", "Jordan Poole", "Jontay Porter", "Kevin Porter Jr.",
  "Michael Porter Jr.", "Otto Porter Jr.", "Bobby Portis", "Kristaps Porzingis", "Dwight Powell",
  "Norman Powell", "Taurean Prince", "Payton Pritchard", "Immanuel Quickley", "Jahmi'us Ramsey",
  "Chasson Randle", "Julius Randle", "Cam Reddish", "JJ Redick", "Paul Reed",
  "Naz Reid", "Cameron Reynolds", "Nick Richards", "Josh Richardson", "Grant Riller", "Austin Rivers",
  "Andre Roberson", "Duncan Robinson", "Jerome Robinson", "Justin Robinson", "Mitchell Robinson",
  "Glenn Robinson III", "Isaiah Roby", "Rajon Rondo", "Derrick Rose", "Terrence Ross", "Terry Rozier",
  "Ricky Rubio", "D'Angelo Russell", "Domantas Sabonis", "Luka Samanic", "JaKarr Sampson", "Dario Saric",
  "Tomas Satoransky", "Dennis Schroder", "Mike Scott", "Jay Scrubb", "Collin Sexton", "Landry Shamet",
  "Iman Shumpert", "Pascal Siakam", "Chris Silva", "Ben ", "Anfernee Simons", "Deividas Sirvydis",
  "Alen Smailagic", "Marcus Smart", "Ish Smith", "Jalen Smith", "Dennis Smith Jr.", "Tony Snell",
  "Ray Spalding", "Cassius Stanley", "Lamar Stevens", "Isaiah Stewart", "Max Strus", "Edmond Sumner",
  "Jae'Sean Tate", "Jayson Tatum", "Jeff Teague", "Garrett Temple", "Tyrell Terry", "Daniel Theis",
  "Brodric Thomas", "Isaiah Thomas", "Khyri Thomas", "Matt Thomas", "Klay Thompson", "Tristan Thompson",
  "Sindarius Thornwell", "Matisse Thybulle", "Killian Tillie", "Xavier Tillman", "Anthony Tolliver",
  "Obi Toppin", "Juan Toscano-Anderson", "Axel Toupane", "Karl-Anthony Towns", "Gary Trent Jr.",
  "P.J. Tucker", "Rayjon Tucker", "Myles Turner", "Jonas Valanciunas", "Denzel Valentine",
  "Fred VanVleet", "Jarred Vanderbilt", "Anderson Varejao", "Devin Vassell", "Luca Vildoza",
  "Gabe Vincent", "Noah Vonleh", "Nikola Vucevic", "Dean Wade", "Moritz Wagner", "Kemba Walker",
  "Lonnie Walker IV", "John Wall", "Brad Wanamaker", "T.J. Warren", "P.J. Washington", "Yuta Watanabe",
  "Tremont Waters", "Paul Watson", "Quinndary Weatherspoon", "Russell Westbrook", "Coby White",
  "Derrick White", "Hassan Whiteside", "Greg Whittington", "Andrew Wiggins", "Grant Williams",
  "Kenrich Williams", "Lou Williams", "Patrick Williams", "Robert Williams III", "Zion Williamson",
  "D.J. Wilson", "Dylan Windler", "Justise Winslow", "Cassius Winston", "James Wiseman", "Christian Wood",
  "Robert Woodard II", "Delon Wright", "Thaddeus Young", "Trae Young", "Omer Yurtseven", "Cody Zeller", "Ivica Zubac"]
